version: "3"

services:
  gradle_server_exporter:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - APP_URL_LINK=http://localhost
      - APP_PORT=8080
      - APP_LOOP_TIME=60
      - LOG_LEVEL=DEBUG
