groups:
- name: gradle-server-exporter
  rules:
  - alert: GradlePendingRequests
    expr: gradle_ingest_queue{entity="pending} > 1000
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: More than 1000 ({{$value}}) pending requests in the queue

  - alert: GradleComponentReady
    expr: gradle_ready == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "{{$labels.entity}}% component is not in ready state"
      runbook: Check {{$labels.url}} for more details
