---
common:
  # change two variables below according to your k8s environment
  k8s_master_uri: k8s_master_uri
  k8s_ca_base64: k8s_ca_base64

  # token should be hidden for security reasons
  # use variable in your ci/cd
  k8s_token: "{{ env='K8S_TOKEN' }}"
  k8s_namespace: monitoring

  app_port: 8000

  image_path: 'bissquit/gradle-server-exporter'
  image_version: 'v1.5@sha256:42deda07f8352811cbe76f391891061fe7d8f7b8983b92ac25e506d581a6b845'

  templates:
    - template: .*.yaml.j2

env-name:
  app_name: gradle-server-exporter
  file_path: "/app/config/urls.txt"
  urls:
    - url: https://first-url.domain.tld/info/ingest-queue
    - url: https://first-url.domain.tld/ready
